IMAGE_SHAPE = (256, 256, 3)
IMAGE_SHAPE_WITHOUT_CHANNELS = (256, 256)
IMAGE_SIZE = IMAGE_SHAPE[0] * IMAGE_SHAPE[1] * IMAGE_SHAPE[2]

N_CLASSES = 979

MODALITY_LIST = ["Flower", "Leaf", "Fruit", "Stem"]
MODALITY_SET = set(MODALITY_LIST)
